### ISSUE TITLE
Undetected sources in proc_Images 

### ISSUE THREAD

**Issue by YarinMS** [EranOfek/AstroPack#369] opened 2024-01-11 14:33 UTC
Following the pipeline products inspection, we noticed sources which are undetected by the pipeline.
While most of the undetected sources appear next to other stars, there are some isolated sources which haven't been detected as well. 
This happens in every image and in every subframe we examined. 
I attach few examples, 

in`/last10e/data1/archive/LAST.01.10.01/2023/12/14/proc/233328v0/LAST.01.10.01_20231214.233628.186_clear_074+55_010_001_009_sci_proc_Image_1.fits`

![Pasted Graphic 5](https://github.com/EranOfek/AstroPack/assets/118757319/8a7565d2-59f1-4a44-8b61-8ebc5d379c14)

![Pasted Graphic 6](https://github.com/EranOfek/AstroPack/assets/118757319/6953e56e-9966-4dcc-b59a-f50bbb209963)

*SOME* of the undetected sources x,y pixels :
`(X,Y) = (649,662), (1308,775),  (1255,800), (1651,1029), (1548,1056), (1572,1214)`

in `/last10e/data1/archive/LAST.01.10.01/2023/12/14/proc/233328v0/LAST.01.10.01_20231214.233628.186_clear_074+55_010_001_009_sci_proc_Image_1.fits`

![Pasted Graphic 9](https://github.com/EranOfek/AstroPack/assets/118757319/e73e69ad-b6dc-4f3b-9b18-d8c7cc6fa457)

*SOME* of the undetected sources x,y pixels :
`(X,Y) =  (803,1306), (938,1282), (60,406), (159,400), (175,477)`

**Comment by EastEriq** [comment] 2024-01-11 14:37
I also see unexpectedly clear but undetected sources in PTF images, and was looking into it as well. I'm not yet sure, but I think that has to do with the computation of the local variance of the image.

**Comment by EranOfek** [comment] 2024-01-12 15:35
This is likely an artifact of the of the background/variance estimation.
Two possibilities to look into:
1. local biases in the estimation that depend on nearby stars.
2. After the grid of background/variance is created it is interpolated to the entire image. The interpolation scheme is not perfect and may generate artifacts.

**Comment by EranOfek** [comment] 2024-01-14 12:38
The main problem is that these sources are found, but then removed by the RemoveBadSources option.
The source of the problem is in the imProc.sources.cleanSources function.
For example, binary stars were removed due to a large shift between the PEAK position and the 1st moment position.
Changed default max shift from 1 to 1.5 pix.
Some other stars were removed due to large diff. between the annulus back and image back.
Revising the cleanSources function.

**Comment by EastEriq** [comment] 2024-01-14 14:33
I beg to differ. In this case for instance the clear source at the center of the image (circled in red, since it is in the GAIA spectral catalog, but without a yellow marker, denoting the result of `imProc.sources.findMeasureSources`) 
![image](https://github.com/EranOfek/AstroPack/assets/16066531/7ce9d2c4-961a-42ac-8a34-e2fe67709e26)
is not found even with `RemoveBadSources=false`.
![image](https://github.com/EranOfek/AstroPack/assets/16066531/5edd576d-0db4-4985-8c93-25b53e369898)
which obviously marks a lot of other junk.
(I'm referring to the upper star, not that in saturation below it, which is tagged as saturated anyway)

Here is a zoom in to the values of image, computed background and variance, in a 60x60 neighborhood
![image](https://github.com/EranOfek/AstroPack/assets/16066531/901d2ce3-1c93-4fc0-847b-fc92c6f3329f)
The background is produced by `imProc.background.background(AI, 'SubSizeXY',[32,32],'Overlap',16)`.

The image is the second subimage in `/raid/enrico/PTF/2ndTake/images/level1/proc/2016/11/10/f14/c4/p5/v1/PTF_201611105117_i_p_scie_t121654_u030037655_f14_p001793_c04.fits` on euler, and we are talking of the source at coordinates ~[1820,1754].

**Comment by EastEriq** [comment] 2024-01-14 14:58
No improvement observed with your lastest commit.
![image](https://github.com/EranOfek/AstroPack/assets/16066531/132f2743-8921-45fa-80a1-766edd69ede7)

On this particular image, I spotted already 9 cases like that, and counting.

**Comment by EranOfek** [comment] 2024-01-14 15:33
This is likely because your BackSizeXY is too small.
In this case, the back and var are overestimated due to the fact that most of the region of the background sub image is dominated by the star.
Try to use [128 by 128]

**Comment by EastEriq** [comment] 2024-01-14 16:07
Been there, done that, no way. With larger windows more sources are missed. The following is with [256,256]. Note that not only the three sources circled in red anre not indentified, but also two other weaker ones but yet clear, above the middle one.
![image](https://github.com/EranOfek/AstroPack/assets/16066531/57cc65e4-4017-4930-8b4e-4d933bca4b0c)

**Comment by EastEriq** [comment] 2024-01-14 16:53
In fact it is even the opposite. Background computation on [16,16] does capture the central source:
![image](https://github.com/EranOfek/AstroPack/assets/16066531/30e9b3f3-34c8-4700-b079-866a60d0a2f9)
I guess we'll have to descend the bowels of how the peak is identified.

**Comment by EranOfek** [comment] 2024-01-15 06:37
1. findMeasureSources creating mask if doens't exist [dev1 d18f76fb]
2. I can't reproduce the PTF Halpha results. In fact using the default parameters:
AI=imProc.sources.findMeasureSources(AI,'RemoveEdgeDist',5) I get very nice results including CR removal.
If you like to see the results without CR removal use:
AI=imProc.sources.findMeasureSources(AI,'RemoveEdgeDist',5,'FlagCR',false)

Closing. Please check and reopen if needed.

**Comment by EastEriq** [comment] 2024-01-15 11:16
Well, no, the latest addition doesn't help in my reference case of `PTF_201611105117_i_p_scie_t121654_u030037655_f14_p001793_c04.fits` subimage 2.

I have been somewhat more systematic in my tests though. I now compiled a list of 13 problematic sources, and I made a script for testing how many of them are correctly found with this or that analysis parameter. 9 of them present on the GAIA spectral catalog, and 4 not, but yet very clear on the ds9 image (sometimes close to other source, still separated).

The result is:
- many sources were excluded because `imProc.mask.maskTracks()` marked them erroneously as `'Streaks'`, which I used to filter out with `imProc.sources.findMeasureSources(...,'BadBitNames')`. I can comment out my call to `imProc.mask.maskTracks()` because anyway the masking is already done in the PTF sources, or include `Streaks`.
- Furthermore, a few sources are flagged as `'ColumnHigh'` by my `imProc.mask.maskBadColumns()`, and I was excluding them as well. For this test image, maybe I can sip the test because it is not crucial, other worse images may benefit from it. 
- Still, at optimum I detect only 10 out of these 13 sources. The size upon which  background computed does not look anymore critical, the result is 10/13 if I use [256,256] as much as 128 or 64 or 32. (empty, [8,8] or [16,16] give a few less).

Here are the images of the three still undetected sources of my list:

[1115,900] (in GAIA) 
![image](https://github.com/EranOfek/AstroPack/assets/16066531/9f4c19b3-c1e6-4ef9-99b2-caf64bb0323b)

[1309,615] not in GAIA 
![image](https://github.com/EranOfek/AstroPack/assets/16066531/56ceba10-7c78-4106-a139-371b38b362e2)

[1037,1535] not in GAIA 
![image](https://github.com/EranOfek/AstroPack/assets/16066531/c0872eb4-95f4-44db-b612-abed7af51b5d)

**Comment by EranOfek** [comment] 2024-01-18 09:20
Is this your ref image:
/raid/enrico/PTF/2ndTake/images/level1/proc/2016/11/10/f14/c4/p5/v1/PTF_201611105117_i_p_scie_t121654_u030037655_f14_p001793_c04.fits

Inspecting this image at the corrdinates you listed suggest that this is a different field.
Are these coordinates in the cropped image?

In any case, running with default parameters:
```
AI=imProc.background.background(AI);
AI=imProc.sources.findMeasureSources(AI)
```
I am happy with the results.

**Closed by EranOfek** 2024-01-18 09:20 UTC
