### ISSUE TITLE
`DS9analysis.getMask` doesn't point-click-retrieve the mask value in the first frame if two are displayed 

### ISSUE THREAD

**Issue by EastEriq** [EranOfek/AstroPack#422] opened 2024-03-13 10:24 UTC
```
>> D9 = DS9analysis;
>> D9.load(AI); % double AstroImage with masks
>> D9.getMask % and click on the first frame on an interesting feature
Select point in ds9 using mouse

ans =

  0×1 empty cell array
```
The problem is likely in`DS9analysys.getXY`, which returns the second AstroImage even if the first was clicked. It may thus affect other methods using it, like `.dist`, `.radial`, `.moments`, `forcedPhot`, `.getBack`, you name it.

**Comment by EastEriq** [comment] 2024-03-13 10:37
Ok, the issue here is that at https://github.com/EranOfek/AstroPack/blob/e9aafcf50bfeacd21b9f9a13f2f97b10296c0666/matlab/image/%40DS9analysis/DS9analysis.m#L669 the frame currently selected in ds9 is retrieved _before_ the click. In my test above I was clicking in frame 1 when frame2 was highlighted.

**Comment by EastEriq** [comment] 2024-03-13 11:16
Something should perhaps be done inside `ds9.ginput` so that the frame where the cursor is being moved becomes the current one. I had a quick look at the xpaset commands but didn't come up with any idea. For the moment I'm only committing a change where I moved the  block of line 669 after the click, hoping that someone returns on it later.

**Comment by EranOfek** [comment] 2024-03-14 11:14
I can not recreate the problem.
When I use DS9analysis/getXY on an image in ds9 in which two frames are presented, it returns the correct coordinates regardless of which frame is highlighted.
Closing.

**Comment by EastEriq** [comment] 2024-03-14 17:27
Not true for `DS9analysis.getMask`, therefore not solved, I reopen.

Test case:
```
AI=[AstroImage,AstroImage];
AI(1).Image=rand(30,30);
AI(2).Image=rand(80,80);
AI(1).MaskData.Dict=BitDictionary;
AI(2).MaskData.Dict=BitDictionary;
AI(1).MaskData.Image=ones(size(AI(1).Image));
AI(2).MaskData.Image=2*ones(size(AI(2).Image));
D9=DS9analysis;
D9.load(AI);
```
Now try `D9.getMask`. If you clicked on the first image you should get 'Saturated', but if the second frame is highlighted you get 'LowRN', and viceversa. Moreover you may get
```
Index in position 1 exceeds array bounds (must not exceed 30).

Error in DS9analysis/getXY (line 703)
                Val       = AI.Image(Ypix, Xpix);

Error in DS9analysis/getMask (line 1029)
            [X, Y, Val, AI] = getXY(Obj, Coo, 'CooSys',Args.CooSys,
            'CooUnits',Args.CooUnits);
```
if you click over pixels in the frame not highlighted, if the same position is out of coordinate bounds in the other.

**Comment by EranOfek** [comment] 2024-03-15 09:18
So the problem is the following:
getXY gets the correct X,Y position in the correct frame. However, getMask does not know from which frame the position was obtained and assumes it is the active frame.

Since the xpa/crosshair command does not return the frame number, I do not  know how to fix it.

Added a text warning when the code for getMask and getBack is running.
Didn't touch other functions. + added a cautionary note to the help section.
[dev1 9315e8ba]

**Closed by EranOfek** 2024-03-15 09:18 UTC
