### ISSUE TITLE
Pipeline with SaveEpochProduct arguments fails when writing files

### ISSUE THREAD

**Issue by noralinn** [EranOfek/AstroPack#194] opened 2023-07-17 09:54 UTC
On last04w, I called the pipeline with the following arguments following the wiki:

`D.main('StartJD',[2460068.2477], 'EndJD',[2460068.3179],'StopWhenDone',true,'SaveEpochProduct',{'Image','Mask','Cat','PSF'});`

And it failed for all images:

```
15:18:25.578 [INF] pipline.DemonLAST executing pipeline for group 15 - First image: /last04w/data2/archive/LAST.01.04.04/new/LAST.01.04.04_20230503.180304.899_clear_168+56_020_001_001_sci_raw_Image_1.fits
15:18:25.583 [INF] pipeline.DemonLAST / pipeline.generic.multiRaw2procCoadd run time [s]:  340.1
15:24:07.060 [INF] pipline.DemonLAST finish executing pipeline - start saving data
15:24:07.071 [INF] pipeline.DemonLAST / pipeline.generic.multiRaw2procCoadd run time [s]:  340.1
[ERR] pipeline.DemonLAST try error: Number of elements in WriteHeader must be 1 or equal to the number of products / funname: writeProduct @ line: 121
[ERR] Exception: id= msg=Number of elements in WriteHeader must be 1 or equal to the number of products
[ERR] stack: Ind=1; FunName=writeProduct; line=121
[ERR] stack: Ind=2; FunName=DemonLAST.main; line=1568
[ERR] pipeline.DemonLAST: 20 images moved to failed directory
15:24:12.271 [INF] pipeline.DemonLAST / pipeline.generic.multiRaw2procCoadd analyzed 20 images starting at 20230503.175644.803
15:24:12.276 [INF] pipeline.DemonLAST / pipeline.generic.multiRaw2procCoadd run time [s]:  341.5

```

I was suspecting the reason is that SaveEpochProduct has 4 entries, while WriteHeader only has 3?

See line 1567 of DemonLAST

```
% the following call also update the AllSI.ImageData.FileName
[FN_Proc,~,Status] = imProc.io.writeProduct(AllSI, FN_I, 'Product',Args.SaveEpochProduct, 'WriteHeader',[true false true],...
                                                   'Level','proc',...
                                                   'LevelPath','proc',...
                                                   'FindSubDir',true);
```

I tried calling it as:

`D.main('StartJD',[2460068.2477], 'EndJD',[2460068.3179],'StopWhenDone',true,'SaveEpochProduct',{'Image','Mask','Cat'});`

Now it fails while saving the visit products with:

```
>> D.main('StartJD',[2460068.2477], 'EndJD',[2460068.3179],'StopWhenDone',true,'SaveEpochProduct',{'Image','Mask','Cat'});
09:43:33.276 [INF] pipline.DemonLAST executing pipeline for group 1 - First image: /last04w/data2/archive/LAST.01.04.04/new/LAST.01.04.04_20230503.193745.289_clear_168+56_100_001_001_sci_raw_Image_1.fits
09:49:02.897 [INF] pipline.DemonLAST finish executing pipeline - start saving data
[ERR] pipeline.DemonLAST try error: Expected one output from a curly brace or dot indexing expression, but there were 2 results. / funname: FileNames.jd2str @ line: 508
[ERR] Exception: id=MATLAB:index:expected_one_output_from_expression msg=Expected one output from a curly brace or dot indexing expression, but there were 2 results.
[ERR] stack: Ind=1; FunName=FileNames.jd2str; line=508
[ERR] stack: Ind=2; FunName=FileNames.getProp; line=539
[ERR] stack: Ind=3; FunName=FileNames.genFile; line=744
[ERR] stack: Ind=4; FunName=FileNames.genFull; line=932
[ERR] stack: Ind=5; FunName=writeProduct; line=187
[ERR] stack: Ind=6; FunName=DemonLAST.main; line=1575
[ERR] pipeline.DemonLAST: 20 images moved to failed directory
09:49:42.081 [INF] pipeline.DemonLAST / pipeline.generic.multiRaw2procCoadd analyzed 20 images starting at 20230503.193125.173
09:49:42.086 [INF] pipeline.DemonLAST / pipeline.generic.multiRaw2procCoadd run time [s]:  363.3
```

**Comment by EranOfek** [comment] 2023-07-17 11:03
The problem is that the 'WriteHeader' argument is not consistent with the SaveProd argument.
Fixed by changing the default 'WriteHeader' to a vector of 4 elements.

**Comment by EranOfek** [comment] 2023-07-19 13:14
re 2nd error - please investigate.
My guess is that CFITSIO tried to write an existing image.
Not sure why, but try to recreate it.

**Comment by EranOfek** [comment] 2023-08-13 14:17
I am closing this one because I can't recreate this - If seen again please open a new issue with more information.

**Closed by EranOfek** 2023-08-13 14:17 UTC
