### ISSUE TITLE
FileNames ignores absolute path if provided

### ISSUE THREAD

**Issue by noralinn** [EranOfek/AstroPack#294] opened 2023-12-02 21:17 UTC
When calling FileNames with an absolute path it finds the correct images. However, then it ignores it and sets FN.FullPath to the current directory.

I would be more convenient if it set FullPath to the passed value.

```
FN = FileNames('/last04e/data1/archive/LAST.01.04.01/2023/09/16/proc/*/LAST*SN2023ijh*10_sci_proc_Image_1.fits')

FN = 

  FileNames with properties:

                   ProjName: {1×500 cell}
                       Time: {1×500 cell}
                     Filter: {1×500 cell}
                    FieldID: {1×500 cell}
                    Counter: [1×500 double]
                      CCDID: [1×500 double]
                     CropID: [1×500 double]
                       Type: {1×500 cell}
                      Level: {1×500 cell}
                    Product: {1×500 cell}
                    Version: [1×500 double]
                   FileType: {1×500 cell}
                   FullPath: '/home/ocs/Desktop/SNFlareSearch'
                   BasePath: '/euler1/archive/LAST'
    BasePathIncludeProjName: 1
                BasePathRef: '/euler1/archive/LAST'
                     SubDir: ''
                   TimeZone: 2
                   UserData: []


FN.genFull

ans =

  500×1 cell array

    {'/home/ocs/Desktop/SNFlareSearch/LAST.01.04.01_20230917.000608.317_clear_SN2023ijh_001_001_010_sci_proc_Image_1.fits'}
    {'/home/ocs/Desktop/SNFlareSearch/LAST.01.04.01_20230917.000628.321_clear_SN2023ijh_002_001_010_sci_proc_Image_1.fits'}
    {'/home/ocs/Desktop/SNFlareSearch/LAST.01.04.01_20230917.000648.345_clear_SN2023ijh_003_001_010_sci_proc_Image_1.fits'}
    {'/home/ocs/Desktop/SNFlareSearch/LAST.01.04.01_20230917.000708.343_clear_SN2023ijh_004_001_010_sci_proc_Image_1.fits'}
    {'/home/ocs/Desktop/SNFlareSearch/LAST.01.04.01_20230917.000728.343_clear_SN2023ijh_005_001_010_sci_proc_Image_1.fits'}
...

```

**Comment by EranOfek** [comment] 2023-12-03 07:28
Use:
FileNames.generateFromFileName
with the 'FullPathFromFileName',true option.

**Comment by EastEriq** [comment] 2023-12-03 08:32
duplicate of #271, actually?

**Comment by noralinn** [comment] 2023-12-05 12:17
Typo in FileNames line 301 it says

Args.FullPathFtomFileName logical = false;


I didn't fix it myself, because I wasn't sure how to do that with the stable version mechanism.

I also think that the default should be true. If a full path name is provided the function should use it. If it's a relative path use the relative one.

**Comment by EranOfek** [comment] 2023-12-05 13:22
1. Why are you saying that this is a typo? This is a valid matlab syntax.
2. I don't want to change the default without testing its effect on the
pipeline. If you test the pipeline with the new default, then we can
consider modifying the default.

**Closed** 2023-12-10 09:11 UTC
