### ISSUE TITLE
`imProc.calib.photometricZP` doesn't correct magnitude consistently for all subimages

### ISSUE THREAD

**Issue by EastEriq** [EranOfek/AstroPack#181] opened 2023-07-02 10:29 UTC
The following plots are
```
for k=1:NsubImages
    semilogy(AI(k).Table.MAG_PSF,AI(k).Table.MAGERR_PSF,'.')
    hold all
end
hold off
xlabel('magnitude'); ylabel('magnitude error')
```
The first is before running `[AI, ZP, PhotCat] =imProc.calib.photometricZP(AI)`
![image](https://github.com/EranOfek/AstroPack/assets/16066531/8ad7499a-6d09-4aec-aed7-42e591e70746)

the second is after it
![image](https://github.com/EranOfek/AstroPack/assets/16066531/3e72f037-77df-43ea-abb3-541129163e19)

**Comment by EastEriq** [comment] 2023-07-02 10:38
Using different subimage splits, it is always the plot for subimage 1 which is offset, the others still collapse

**Comment by EastEriq** [comment] 2023-07-02 10:39
maybe still connected to #174?

**Comment by EranOfek** [comment] 2023-07-02 12:44
The problem is due to failure of astrometryRefine.
closing.

**Closed by EranOfek** 2023-07-02 12:44 UTC
