### ISSUE TITLE
Calib and failed directories changed path.

### ISSUE THREAD

**Issue by YarinMS** [EranOfek/AstroPack#198] opened 2023-07-21 11:02 UTC
We are all familiar with the components of a telescope directory, for instance:
<img width="1006" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/d8eb9c43-c7f2-4e21-b743-5677d690d025">

While trying to run the pipeline on last08 and later on last02 we noticed a disturbing problem:
 
<img width="1006" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/b0795256-a85b-4191-aacf-1a08625044fc">
 
 Both of these computers had no Calib, and failed directories. Which is REALLY weird since they both had a chance to run the pipeline multiple times and surley have some calibraeted files.

After looking for these files over the disk we get that :

/last08w/**_data1_**/archive/LAST.01.08.03/calib is actually at /last08w/**_data2_**/archive/LAST.01.08.03/calib

And
 /last08w/**_data2_**/archive/LAST.01.08.04/calib is at /last08w/**_data1_**/archive/LAST.01.08.04/calib.

This switch hurt the pipeline from locating calibration images. since the pipeline object store the correct paths like this : 

<img width="489" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/f405f9d5-cc4e-4786-ba3e-28fe31dc17c8">

One way to pass it is to change the paths to the right directories, when we get the following error :
<img width="755" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/3dbdd906-6f62-4db0-907f-81e56ec7eaaf">

change the path to the directory WRONG location :
<img width="775" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/096d5901-c965-49a3-9224-86cff9b40143">

So the pipeline will run only after changing its default 'CalibPath'. I think that this is due to a bug who switched the directories paths and probably not only on these 2 computers.  Please check what changed. And let me know if something is not clear.

**Comment by blumzi** [comment] 2023-07-21 14:47
Please remind me to take care of this. - ArieOn 21 Jul 2023, at 14:02, YarinMS ***@***.***> wrote:﻿
We are all familiar with the components of a telescope directory, for instance:

While trying to run the pipeline on last08 and later on last02 we noticed a disturbing problem:

Both of these computers had no Calib, and failed directories. Which is REALLY weird since they both had a chance to run the pipeline multiple times and surley have some calibraeted files.
After looking for these files over the disk we get that :
/last08w/data1/archive/LAST.01.08.03/calib is actually at /last08w/data2/archive/LAST.01.08.03/calib
And
/last08w/data2/archive/LAST.01.08.04/calib is at /last08w/data1/archive/LAST.01.08.04/calib.
This switch hurt the pipeline from locating calibration images. since the pipeline object store the correct paths like this :

One way to pass it is to change the paths to the right directories, when we get the following error :

change the path to the directory WRONG location :

So the pipeline will run only after changing its default 'CalibPath'. I think that this is due to a bug who switched the directories paths and probably not only on these 2 computers.  Please check what changed. And let me know if something is not clear.

**Comment by EranOfek** [comment] 2023-07-21 15:54
please be careful when running the pipeline.
Always check if the pipeline service is operational.

**Comment by blumzi** [comment] 2023-07-23 11:04
Hi,

I'm writing a new section for last-tool to address the pipeline.  All
sections have a 'check' and an 'enforce'  function

So, we'll have a check for calib directories as follows (taken from
last10e and last10w)


/last10e/data1/archive/LAST.01.10.01/calib
/last10e/data2/archive/LAST.01.10.02/calib

/last10w/data1/archive/LAST.01.10.03/calib
/last10w/data2/archive/LAST.01.10.04/calib


What else should I check for?

Cheers,

- Arie

**Comment by EranOfek** [comment] 2023-07-23 18:31
I don't think this is the problem.
As far as I understand, the problem is that this directory and its content
disappeared...
eran

**Comment by YarinMS** [comment] 2023-07-26 09:44
The problem is that directories such : `data1/archive/LAST.01.0#.0(1/3)` moved to `data2/archive/LAST.01.0#.0(1/3)`
and `data2/archive/LAST.01.0#.0(2/4)` moved to `data1/archive/LAST.01.0#.0(2/4)` almost in all computers. (besides last10 and last04.)
there are few computers that I couldn't find such directories at all, see report below.

To change it, in all computers I copied the "calib" and "failed" directories back to their original  path by `cp  -r` and not by `mv` just to be extra careful, but these folder should be deleted from their alternative path since most of them are heavy ( memory wise ).

here is a short report for all computers

**LAST01** :
`data2/archive/LAST.01.01.01/(calib/failed)` moved to `data1/archive/LAST.01.01.01/(calib/failed)`
`data1/archive/LAST.01.01.02/(calib/failed)`  moved to `data2/archive/LAST.01.01.02/(calib/failed)`
`data2/archive/LAST.01.01.03/(calib/failed)` moved to `data1/archive/LAST.01.01.03/(calib/failed)`
`data1/archive/LAST.01.01.04/(calib/failed)`  moved to `data2/archive/LAST.01.01.04/(calib/failed)`

**LAST02**
`data2/archive/LAST.01.02.01/(calib/failed)` moved to `data1/archive/LAST.01.02.01/(calib/failed)`
`data1/archive/LAST.01.02.02/(calib/failed)`  moved to `data2/archive/LAST.01.02.02/(calib/failed)`
`data2/archive/LAST.01.02.03/(calib/failed)` moved to `data1/archive/LAST.01.02.03/(calib/failed)`
`data1/archive/LAST.01.02.04/(calib/failed)`  moved to `data2/archive/LAST.01.02.04/(calib/failed)`

**LAST03**
- LAST.01.03.01  - Unchanged
- LAST.01.03.02 - Unchanged
`data1/archive/LAST.01.03.04/calib`  moved to `data2/archive/LAST.01.02.04/calib`
- for LAST.01.03.04 no failed directory found.
- for LAST.01.03.03 no calib or failed directory found.
**I can create such directories with your permission**, but this is really interesting where they are.

**LAST04**
directories are in the right path for this mount. - Unchanged


**LAST05**
LAST.01.05.01  - Unchanged

- for LAST.01.05.02 no calib or failed directory found. 

LAST.01.05.03  - Unchanged
LAST.01.05.04  - Unchanged

**LAST06**
- In cdcam1 we have an additional 'LAST.01.06.01' directory. this will result in a wrong path for calib and failed :
`/last06e/data1/archive/LAST.01.06.01/LAST.01.06.01/(calib or failed)`
which also contain "new" and "log directories". I can fix it, meaning to combine the new and log directories from `/last06e/data1/archive/LAST.01.06.01/` . **I'll do it after your approval.** , image to demonstrate:
<img width="485" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/28bba50b-078f-45b4-a2e3-00794c59ae29">

- Cant find calib and failed directories in `/last06e/data1/archive/LAST.01.06.02` like I did for previous computers.
- LAST.01.06.03 - Unchanged
- LAST.01.06.04 -Unchanged


**LAST08**
-`data2/archive/LAST.01.08.01/(calib/failed)` moved to `data1/archive/LAST.01.08.01/(calib/failed)`
- LAST08w - no connection

**LAST10**
directories are in the right path for this mount. - Unchanged


**TO DO **
with your permission I will :
- create failed directory for LAST.01.03.04.
- create failed and calib for LAST.01.03.03.
- create failed and calib for LAST.01.05.02.
- connect between multiplicity of directories in LAST.01.06.01
- create failed and calib for LAST.01.06.02.
- from all computers move all failed images back to new
This solution, to make directories, doesn't solve the problem, where did all this data disappear too ?
BUT, if we want to run the pipeline we need such directories in our BasePath.

**Comment by EranOfek** [comment] 2023-08-30 07:24
Yarin - is the new di also switched?
Arie - is it possible that after reboot data1 and data2 change roll?

**Comment by YarinMS** [comment] 2023-08-31 09:17
"new" directory was in the right path.

My guess is it could be related to the following feature of the pipeline.DemonLAST :  

When initiating the object on any computer, it has a default camera defined. For eastern machines it is camera 1 and for western it is camera 3 (and the paths of their directories).
Image for reference (last02w):
![image](https://github.com/EranOfek/AstroPack/assets/118757319/ae42a384-7384-463e-a3ae-e741697b1750)

To "reproduce" the error, lets assume someone used the pipeline to process data from CamNumber = [] = 3, with the general command : 
`D.main('StopWhenDone',true,'StartJD',[14 04 2004],'EndJD',[14 04 2014],'SaveEpochProduct',{'Image','Mask','Cat',[]})`

Which will process the images from the "new" directory in /data1/LAST.01.02.03. Great.
Now, the innocent user would probably like to process images taken from camera 4,  s/he does so by changing ONLY the CamNumber argument of the pipeline.
Image for reference :
![image](https://github.com/EranOfek/AstroPack/assets/118757319/92b2ede6-7395-4c39-a854-0855c0eff953)

As a result, processed images from the camera #4 are targeted to inhibit data1/LAST.01.02.04 And therefore creating the "migration" of the calib, and failed directories ('new' and 'log' as well). If true, it could also be that it process calib images of one telescope and store them for the other. many more problems could emerge.
Maybe there should be a safe mechanism that prevent this human error.

What the user should do is ALSO changing the `DataDir` argument.
Image for reference :
![image](https://github.com/EranOfek/AstroPack/assets/118757319/6ba98bac-5045-474e-8230-b491c4644785)


Although this might not be the reason for the above issue. I think it's important to make sure we can prevent such creation of these directories in their wrong path.
A really comfortable and user friendly feature could be an Argument to` D.main(...,'CameraNum','4')`.

**Comment by EranOfek** [comment] 2023-08-31 10:14
it is not clear to me who is moving the directories...

**Comment by EranOfek** [comment] 2023-12-14 07:37
Can we close this one?

**Comment by YarinMS** [comment] 2023-12-14 07:39
I haven't encountered any similar case since.

**Comment by EranOfek** [comment] 2023-12-25 11:32
The reason is unknown and was not seen again.
Closing, but need to watch for this.

**Closed by EranOfek** 2023-12-25 11:32 UTC
