### ISSUE TITLE
Inconsistent field-to-coordinates assignment

### ISSUE THREAD

**Issue by RuslanKonno** [EranOfek/AstroPack#434] opened 2024-04-16 19:44 UTC
Disagreement in RA/Dec between images with the same Field ID.

e.g.: 
the reference image `/marvin/references/1740/LAST.01.01.01_20240309.002455.399_clear_1740_000_001_020_sci_coadd_Image_1.fits` has RA/Dec coordinates (162, 27)
while the image `/marvin/LAST.01.01.01/2024/03/03/proc/213523v0/LAST.01.01.01_20240303.213513.511_clear_1740_000_001_020_sci_coadd_Image_1.fits ` has RA/Dec coordinates (167, 75) 

The coordinates are very off, so something clearly went wrong - not sure yet what the cause is or how many other images might have a similar issue.

**Comment by agioffe** [comment] 2024-04-17 07:18
Did you check positions of some well-known objects in each of the fields? Do they appear where they should?

**Comment by RuslanKonno** [comment] 2024-04-17 08:09
For one, just to show, the images do look like completely different fields.

![Screenshot from 2024-04-17 10-52-57](https://github.com/EranOfek/AstroPack/assets/51087294/7f21bc21-b4ce-40e3-a2c9-1b03fc7c2790)

Looking for some prominent objects, I do find them all on Simbad so it looks like the coordinates are correct wrt. to the image. So it seems like either of the images received the wrong target field or was pointed in the wrong direction.

**Comment by agioffe** [comment] 2024-04-17 08:17
OK, so it looks like an issue of the pointing model as it was on that days. Let's just keep a list of such cases, probably, we'll see more of them, once we run the difference image pipeline further.

**Comment by EranOfek** [comment] 2024-04-17 08:22
I suspect this is due to a problem with the goTo function. One possibility
is that it failed due to a timeout. It will be good to consult with Enrico.

**Comment by EastEriq** [comment] 2024-04-17 08:39
I can only deal with this if it is reproducible.
Find me a repeatable case where `.goTo` is commanded one position, and the mount goes somewhere else, then we talk.

**Comment by EranOfek** [comment] 2024-04-17 09:54
is there a log file in which the mount reports on timeouts?

**Comment by EastEriq** [comment] 2024-04-17 10:15
Only if specially activated beforehand on the whole MATLAB session. For past takes, not.

**Comment by EranOfek** [comment] 2024-05-08 07:47
Closing due to ack oinformation.

**Closed by EranOfek** 2024-05-08 07:47 UTC
