### ISSUE TITLE
celestial.coo.convert2equatorial returns very large shifts for some coordinates

### ISSUE THREAD

**Issue by noralinn** [EranOfek/AstroPack#355] opened 2024-01-04 14:27 UTC
Found weird behavior while looking into pointing model issue and decided to test convert2equatorial for random coordinates. It's used by goToTarget.

It returns very large shifts for some locations (near Galactic or Ecliptic plane?). I ran the following code:

```
[JRA, JDEC, ~] = celestial.coo.convert2equatorial(RA, DEC);

[D, A] = celestial.coo.sphere_dist(RA, DEC, JRA, JDEC, 'deg');

offsetRA = D.*sin(A).*RAD;
offsetDEC = D.*cos(A).*RAD;

```

Here the large values:
RA	         Dec	 JRA	JDec	offsetRA offsetDEC
45.72	-46.33	48.52	-48.29	1.863	-1.997
160.41	58.90	157.39	65.33	-1.264	6.466
92.70	15.91	89.22	17.94	-3.316	2.063
136.96	53.73	340.65	-5.84	-65.465	110.447
256.04	12.93	257.78	13.95	1.688	1.029
95.50	19.12	98.13	17.49	2.507	-1.611
310.58	-51.04	317.29	-44.11	4.825	6.709
175.54	59.90	175.66	61.66	0.060	1.768
306.82	-49.22	314.68	-41.55	5.890	7.375
35.67	-51.07	31.78	-47.29	-2.643	3.710
162.14	59.61	161.69	60.92	-0.221	1.312
86.14	4.13	88.36	2.81	2.214	-1.316
33.17	-52.91	35.11	-54.60	1.125	-1.699
66.88	-25.00	64.14	-23.25	-2.517	1.720
62.14	-31.58	70.01	-36.07	6.365	-4.728
97.16	21.11	98.70	20.15	1.446	-0.950
64.52	-29.62	65.90	-30.46	1.183	-0.841
51.81	-41.14	47.72	-38.08	-3.221	2.979

and a figure:
![Screenshot from 2024-01-04 16-19-56](https://github.com/EranOfek/AstroPack/assets/14293969/85635b53-02ab-4c90-b611-e38e3497e327)

**Comment by noralinn** [comment] 2024-01-04 14:39
Here the entire code that produces the above figures. It's on last08e:~/Desktop/nora/testEquinoxConversion.m


```

RAD = 180./pi;

NPoints = 2000;

rng("default")
RA = rand(NPoints,1).*360;
DEC = (rand(NPoints,1)-0.5).*180;

[JRA, JDEC, ~] = celestial.coo.convert2equatorial(RA, DEC);

[D, A] = celestial.coo.sphere_dist(RA, DEC, JRA, JDEC, 'deg');

offsetRA = D.*sin(A).*RAD;
offsetDEC = D.*cos(A).*RAD;

fprintf("RA\tDec\tJRA\tJDec\tdiffRA\tdiffDec\n")
for i = 1:NPoints
    if (abs(offsetRA(i,1))>1 + (abs(offsetDEC(i,1))>1)) > 0 
        
        fprintf("%.2f\t%.2f\t%.2f\t%.2f\t%.3f\t%.3f\n", ...
            RA(i,1), DEC(i,1),JRA(i,1), JDEC(i,1), ...
            offsetRA(i,1),offsetDEC(i,1))
        %offsetRA(i,1) = offsetRA(i,1)/abs(offsetRA(i,1));
        %offsetDEC(i,1) = offsetDEC(i,1)/abs(offsetDEC(i,1));

    end
end

fig = figure;
colormap(fig,jet);
scatter(RA, DEC, 10, offsetRA, 'filled'); 
colorbar;
caxis([-1 1]);
title('Offset RA');
xlabel('RA');
ylabel('Dec');
%exportgraphics(fig,'~/Desktop/nora/plots/testEquinoxConversion_offsetRA.png', ...
%    'Resolution',300)

fig = figure;
colormap(fig,jet);
scatter(RA, DEC, 10, offsetDEC, 'filled'); 
colorbar;
caxis([-1 1]);
title('Offset Dec');
xlabel('RA');
ylabel('Dec');
%exportgraphics(fig,'~/Desktop/nora/plots/testEquinoxConversion_offsetDec.png', ...
%    'Resolution',300)
```

**Comment by noralinn** [comment] 2024-01-04 15:12
I'm suspecting that the line is the horizon and that the large deviations are due to refraction very close to the horizon. So maybe there is no bug here...

**Comment by noralinn** [comment] 2024-01-04 15:27
Here, the same figures showing only points for Altitude>20 deg. Looks ok to me!

![testEquinoxConversion_offsetRA](https://github.com/EranOfek/AstroPack/assets/14293969/1da6c6dd-a10f-4d22-ad89-c7af87ccf298)
![testEquinoxConversion_offsetDec](https://github.com/EranOfek/AstroPack/assets/14293969/ff705af3-2b4b-45d9-9472-5938533701ae)

**Comment by EastEriq** [comment] 2024-01-04 15:27
Indeed, if you call in your code  `[JRA, JDEC, ~] = celestial.coo.convert2equatorial(RA, DEC,'ApplyRefraction',false)`  you get half of the offsets ~1e-7, and half of them NaN. As for not getting them exactly zero, there may be something in common with #253.

**Comment by EranOfek** [comment] 2024-01-05 09:06
I can't reproduce te first plot.
I tested the function and compared it to external sources:
[JRA, JDEC, ~] = celestial.coo.convert2equatorial(180,0,'InCooType','J2000','OutCooType','J2024','ApplyRefraction',false)
It works well.

Note that by default the function applies atmospheric refraction.

There is another problem with the way we apply the distortions. I will write something about it later.

**Comment by EastEriq** [comment] 2024-01-05 09:17
I did reproduce Nora's first plot, with `'ApplyRefraction',true` (or without, i.e. default), which is what Nora herself is saying.

**Comment by EranOfek** [comment] 2024-01-05 09:36
Yes - with ApplyRefraction=true, I do get it.
progress.

**Comment by EranOfek** [comment] 2024-01-05 12:32
This is not a bug - what you see here is the refraction angle near the horizon of the observer.
Near the horizon, the refraction angle is large.

**Comment by EranOfek** [comment] 2024-01-08 15:22
I am declared this function as obsolete.
Closing

**Comment by EranOfek** [comment] 2024-01-18 09:05
This function is obsolete.

**Closed by EranOfek** 2024-01-18 09:05 UTC
